export enum WaslIntegrationLogTypeEnum {
    OperatingCompany_RegisterCompany = 1,
    OperatingCompany_RegisterIndividual = 2,
    OperatingCompany_UpdateContactInfo = 3,
    OperatingCompany_Get = 4,
    OperatingCompany_Delete = 5,
    Vehicle_Register = 10,
    Vehicle_UpdateIMEI = 11,
    Vehicle_Get = 12,
    Vehicle_Delete = 13,
    Driver_Register = 20,
    Driver_Update = 21,
    Driver_Get = 22,
    Driver_Delete = 23,
    Taxi_StartTrip = 30,
    Taxi_EndTrip = 31,
    Warehouse_Register = 40,
    Warehouse_Update = 41,
    Warehouse_Delete = 42,
    Warehouse_Get = 43,
    Inventory_Register = 50,
    Inventory_StatsRegisteration = 51,
    Inventory_Update = 52,
    Inventory_Delete = 53,
    Vehicle_StoringCategory = 54
  }